#define Wire_has_loose_ends	1
#define This_wire_connects_more_than_one_data_sink_but_has_no_source	2
#define Wire_is_a_member_of_a_cycle	3
#define You_have_connected_two_terminals_of_different_types	4
#define You_have_connected_two_arrays_of_different_dimensions	5
#define Scalar_array_conflict	6
#define You_have_connected_numeric_data_types_that_have_incompatible_units	7
#define You_have_connected_two_clusters_with_different_contents	8
#define Missing_assignment_to_tunnel	9
#define Multiple_assignment_to_tunnel	10
#define SubVI_is_missing	11
#define SubVI_is_not_executable	12
#define SubVI_is_already_running	13
#define Bad_linkage_to_subVI	14
#define Contains_unwired_or_bad_terminal	15
#define You_have_connected_this_wire_to_more_than_one_data_source	16
#define Object_code_is_not_loaded	17
#define Recursive_reference	18
#define LabVIEW_subroutine_link_error	19
#define Refnum_conflict	20
#define Function_conflict	21
#define Unassigned_sequence_local_s_	22
#define N_is_not_wired_and_there_are_no_indexing_inputs	23
#define Hidden_front_panel_control_has_undefined_type	24
#define Constant_has_undefined_type	25
#define Unwired_selector	26
#define Function_not_supported_by_this_version	27
#define Bad_linkage_to_method_information	28
#define Subroutine_priority_VI_cannot_contain_an_asynchronous_node	29
#define Subroutine_priority_VI_cannot_call_a_non_subroutine_priority_subVI	30
#define No_item_with_this_name	31
#define Cluster_is_invalid_or_empty	32
#define You_have_initialized_some_shift_register_elements_but_not_all_of_them	33
#define Bad_unit_syntax	34
#define Shift_register_data_type_is_undefined	35
#define Shift_register_is_unwired_from_inside_the_loop	36
#define Enumeration_conflict	37
#define SubVI_is_in_interactive_retrieval_mode	38
#define SubVI_is_in_panel_order_or_cluster_order_mode	39
#define Unwired_input	40
#define Unassigned_output	41
#define No_library_specified	42
#define No_function_specified	43
#define Library_not_found	44
#define Function_not_found_in_library	45
#define Function_is_no_longer_supported	46
#define Invalid_return_type	47
#define Invalid_parameter_type	48
#define Required_input_is_not_wired	49
#define Class_conflict	50
#define Format_specifier_type_mismatch	51
#define Unknown_format_specifier	52
#define Too_many_format_specifiers	53
#define Too_few_format_specifiers	54
#define Case_does_not_have_selector_value	55
#define No_case_for_some_selector_values	56
#define Selector_values_have_wrong_type	57
#define Selector_values_are_not_unique	58
#define Reserved_parameter_name	59
#define Invalid_parameter_name	60
#define Duplicate_parameter_name	61
#define Global_VI_is_missing	62
#define Conditional_terminal_is_not_wired	63
#define You_have_connected_a_control_to_a_control	64
#define You_have_connected_an_indicator_to_an_indicator	65
#define This_wire_is_not_connected_to_anything	66
#define Waveform_is_invalid	67
#define More_than_one_index_input_is_wired	68
#define This_variable_is_not_connected_to_anything	69
#define Cluster_items_are_not_named_uniquely	70
#define Invalid_method	71
#define Invalid_property	72
#define Polymorphic_subVI_is_broken	73
#define One_or_more_event_cases_have_no_events_defined	74
#define Event_specified_by_more_than_one_event_case	75
#define Events_specified_by_event_case_are_not_compatible_with_each_other	76
#define Timeout_input_wired_but_Timeout_event_not_handled	77
#define Duplicate_items_selected_in_an_event_data_filter_mode	78
#define Sequence_local_has_sources_on_separate_frames	81
#define No_Event_Selected	82 
#define Dynamic_event_configuration_does_not_match_dynamic_event_registration	83
#define User_event_data_type_is_unnamed_or_has_elements_with_no_names	84
#define Property_Node_is_linked_to_a_strict_typedef	85
#define Array_element_conflict	88
#define You_have_connected_to_a_polymorphic_terminal_that_cannot_accept_this_datatype	91
#define Undirected_tunnel	92
#define Invalid_constructor	93
#define Invalid_refnum_class	94
#define FPGATargetVIBroken	96
#define FPGATargetVIRunning	97
#define FPGATargetNotSelected	98
#define FPGATargetVINotFound	99
#define FPGAPluginNotFound	100
#define CtlNotFoundOnTargetVI	101
#define MethodParamsChanged	102
#define NoMethodSelected	103
#define NoPropertySelected	104
#define AliasNotFound	105
#define AliasNotConfigured	106
#define AliasNotSelected	107
#define NoOpenProject	108
#define EmulationVINotAvail	109
#define EmulationInterfaceErr	110
#define EmulationVIBroken	111
#define ErrCallingPlugin	112
#define FIFOUnconfigured	113
#define MethodUnAvailForTarget	114
#define PropMethUnavailForIOType	115
#define FPGATargetVINotSelected	116
#define HDLInOutUnconfigured	117
#define EnableChainIncorrect	118